version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    volumes:
      - ./softnet_backend/pdf-storage:/app/pdf-storage
      - ./softnet_backend/sofnet_database.sqlite:/app/sofnet_database.sqlite
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
