# Dockerfile for Spring Boot backend
FROM maven:3.9.6-eclipse-temurin-21-alpine as build
WORKDIR /app
COPY softnet_backend/pom.xml ./
COPY softnet_backend/src ./src
RUN mvn -f pom.xml clean package -DskipTests

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
